spring:
  application:
    name: task-api
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    
#logging:
#  pattern:
#    level: ''